### ISSUE TITLE
PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated 

### ISSUE THREAD

**Issue by Rar9** [eileenmcnaughton/nz.co.fuzion.civitoken#53]
With Drupal 9 PHP 7.4.x Im now getting with civicrm 5.34 

PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /var/www/vhosts/xxx/web/sites/default/files/civicrm/ext/nz.co.fuzion.civitoken/civitoken.civix.php on line 246

**Comment by eileenmcnaughton** [comment]
I re-ran [civix](https://docs.civicrm.org/dev/en/stable/extensions/civix/) (which generates that file) by moving into the directory & issuing the command 

```
civix generate:module
```

- running that with the latest version of civix normally fixes that up as it was fixed in civix long ago. However, I didn't spot the relevant change in the commit so I think it might have already been fixed in the codebase. I tagged release 1.8 with the latest code to make sure we are all on the same code
